FROM tensorflow/tensorflow:1.9.0

WORKDIR /tf_sheeran

COPY ./images /tf_sheeran/images
COPY ./train.py /tf_sheeran/retrain.py

EXPOSE 6006

CMD ["python","train.py","--bottleneck_dir=./model/bottlenecks","--model_dir=./model/inception","--summaries_dir=./model/training_summaries/long","--output_graph=./model/retrained_graph.pb","--output_labels=./model/retrained_labels.txt","--image_dir=images"]