FROM tensorflow/tensorflow:1.9.0

WORKDIR /

COPY ./model/retrained_graph.pb /retrained_graph.pb
COPY ./model/retrained_labels.txt /retrained_labels.txt
COPY ./run-model.py /run-model.py
COPY ./*.jpg /
